# Generated by Django 2.0.dev20170120074947 on 2017-02-02 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=2080)),
                ('href', models.CharField(max_length=2083, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=5000)),
                ('text', models.CharField(max_length=3000)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.Page')),
            ],
        ),
        migrations.CreateModel(
            name='PageobjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=200, unique=True)),
                ('auth', models.CharField(max_length=530)),
                ('logtime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.Interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserPageobject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selections', models.IntegerField(default=0)),
                ('pageobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.PageObject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.User')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.Page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.User')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=2083, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(through='popclick.UserInterest', to='popclick.Interest'),
        ),
        migrations.AddField(
            model_name='pageobjectlog',
            name='user_pageobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.UserPageobject'),
        ),
        migrations.AddField(
            model_name='page',
            name='users',
            field=models.ManyToManyField(to='popclick.User'),
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.Website'),
        ),
        migrations.AlterUniqueTogether(
            name='userpageobject',
            unique_together=set([('user', 'pageobject')]),
        ),
    ]
