# Generated by Django 2.0.dev20170120074947 on 2017-02-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
