# Generated by Django 2.0.dev20170120074947 on 2017-02-14 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageobjectInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=1)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.Interest')),
                ('pageobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePageobjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_pageobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.ProfilePageobject')),
            ],
        ),
        migrations.RemoveField(
            model_name='pageobjectlog',
            name='profile_pageobject',
        ),
        migrations.AddField(
            model_name='pageobject',
            name='selections',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='pageobject',
            unique_together=set([('page', 'href', 'selector')]),
        ),
        migrations.DeleteModel(
            name='PageobjectLog',
        ),
        migrations.AlterUniqueTogether(
            name='pageobjectinterest',
            unique_together=set([('pageobject', 'interest')]),
        ),
    ]
