# Generated by Django 2.0.dev20170120074947 on 2017-02-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageobjectInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=1)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.Interest')),
                ('pageobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pageobjectinterest',
            unique_together=set([('pageobject', 'interest')]),
        ),
    ]
