# Generated by Django 2.0.dev20170120074947 on 2017-02-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=1)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.Interest')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.Page')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='pageinterest',
            unique_together=set([('page', 'interest')]),
        ),
    ]
