# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0002_pageobjectlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepageobjectlog',
            name='profile_pageobject',
        ),
        migrations.DeleteModel(
            name='ProfilePageobjectLog',
        ),
    ]
