# Generated by Django 2.0.dev20170120074947 on 2017-02-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0002_auto_20170209_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageobject',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profilepageobject',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='pageobject',
            unique_together=set([('page', 'href', 'selector')]),
        ),
    ]
