# Generated by Django 2.0.dev20170120074947 on 2017-02-28 18:31

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0003_securingtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecuringTest',
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
