# Generated by Django 2.0.dev20170120074947 on 2017-02-28 18:47

from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0004_auto_20170228_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuringTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', fernet_fields.fields.EncryptedTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='auth',
            field=models.CharField(max_length=530),
        ),
    ]
