# Generated by Django 2.0.dev20170120074947 on 2017-02-28 19:41

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0005_auto_20170228_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auth',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
