# Generated by Django 2.0.dev20170120074947 on 2017-02-28 20:02

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0007_auto_20170228_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', fernet_fields.fields.EncryptedTextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popclick.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='SecuringTest',
        ),
    ]
