# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0007_pageobjectinterest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pageobjectinterest',
            unique_together=set([('pageobject', 'interest')]),
        ),
    ]
