# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0008_auto_20170403_1526'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile_po_interestdistance',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='profile_po_interestdistance',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='profile_po_interestdistance',
            name='pageobject',
        ),
        migrations.RemoveField(
            model_name='profile_po_interestdistance',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='profile_po_ticket',
            name='page',
        ),
        migrations.RemoveField(
            model_name='profile_po_ticket',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile_PO_InterestDistance',
        ),
        migrations.DeleteModel(
            name='Profile_PO_Ticket',
        ),
    ]
