# Generated by Django 2.0.dev20170120074947 on 2017-03-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0008_auto_20170228_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='auth',
        ),
    ]
