# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0009_auto_20170403_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageobjectinterest',
            name='level',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='profileinterest',
            name='level',
            field=models.FloatField(default=1),
        ),
    ]
