# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0010_auto_20170403_1622'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilevirtualinterest',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='profilevirtualinterest',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='profilevirtualinterest',
            name='profile',
        ),
        migrations.DeleteModel(
            name='ProfileVirtualInterest',
        ),
    ]
