# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popclick', '0011_auto_20170413_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='href',
            field=models.CharField(max_length=2083),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=set([('website', 'path', 'href')]),
        ),
    ]
