# Generated by Django 2.0.dev20170120074947 on 2017-01-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=3)),
                ('uses', models.IntegerField(default=0)),
            ],
        ),
    ]
