# Generated by Django 2.0.dev20170120074947 on 2017-01-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20170122_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prime',
            name='number',
            field=models.CharField(max_length=1000),
        ),
    ]
